%YAML 1.1
---
vars:
  address-groups:
    HOME_NET: "[192.168.0.0/16]"
    EXTERNAL_NET: "!$HOME_NET"
    SSH_SERVERS: "$HOME_NET"
    HTTP_SERVERS: "$HOME_NET"
    SQL_SERVERS: "$HOME_NET"

  port-groups:
    SSH_PORTS: "22"
    HTTP_PORTS: "80,8080,8000,8888,443"
    SQL_PORTS: "5432"

default-rule-path: /var/lib/suricata/rules
rule-files:
  - suricata.rules      # suricata-updateで取得したルール＋自作ルール（Emerging Threats推奨）

af-packet:
  # 外部ネットワーク接続インターフェース（WAN）の例。実環境では
  # AZAZEL_WAN_IF 環境変数で単一インターフェースを指定するか、
  # azazel のランタイム WAN マネージャ経由で選択することを推奨します。
  # 例: export AZAZEL_WAN_IF=wlan1
  # 下記は複数インターフェースを監視するサンプルです。
  - interface: wlan1
    cluster-id: 99
    cluster-type: cluster_flow
    defrag: yes
    use-mmap: yes
    disable-promisc: no
  - interface: eth0
    cluster-id: 100
    cluster-type: cluster_flow
    defrag: yes
    use-mmap: yes
    disable-promisc: no

outputs:
  - fast:
      enabled: yes
      filename: /var/log/suricata/fast.log
      append: yes

  - eve-log:
      enabled: yes
      filetype: regular
      filename: /var/log/suricata/eve.json
      types:
        - alert:
            tagged-packets: yes
        - flow
        - stats

logging:
  default-log-level: notice
  outputs:
    - file:
        enabled: yes
        level: info
        filename: /var/log/suricata/suricata.log

classification-file: /etc/suricata/classification.config
reference-config-file: /etc/suricata/reference.config